name: LLNEW
favicon: null
layout_spectrum: 0.793065621284768
typography_spectrum: 0.14732092968188226
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.18773195054382086
  lightness: 0.7922719072084874
  saturation: 0.6228657620958984
  rhythmicContrast: 0.45173299429006875
purpose: []
